### ISSUE TITLE
Runtime terminating during boot (killed)

### ISSUE THREAD

**Issue by drew-harris** [rawhat/stratus#3]
While investigating another issue, I setup a local websocket server using Bun and attempted to connect from stratus. When the websocket server wasn't running, the program correctly errored with Econnrefused. However when the server *was* running, the program would hang for a bit then crash with `Runtime terminating during boot (killed)`

No connection was successfully made to the local websockets server. There's a chance I could be doing things wrong as I am new to Gleam, but I pretty much copped the example code line-by-line. 

Running on M1 Macbook Air. Gleam and Erlang installed through homebrew. 

[Here is a reproduction](https://github.com/drew-harris/gleam-discord-bot/tree/reproduction)

It includes the Gleam code, the Bun websockets server, and a javascript client script that demonstrates the connection working properly.

**Comment by rawhat** [comment]
Thanks for the helpful reproduction!  I needed to handle the case that the provided URI does not end in a slash.  It was being parsed as `path = ""` which meant I was not creating a valid HTTP request.

I think this should be fixed on `main`.  I have a couple other things I want to fix before I do another release.  If you want to test it before, you can clone the repo and use a path dependency in your project.  See here:  https://gleam.run/writing-gleam/gleam-toml/

I'll leave this open until you have a chance to try again.  Please let me know if it resolves it 😄
