### ISSUE TITLE
TLS handshake failure when connecting to Discord Gateway

### ISSUE THREAD

**Issue by drew-harris** [rawhat/stratus#4]
Getting this error when trying to connect to the Discord Websocket Gateway
```
=NOTICE REPORT==== 14-Mar-2024::16:19:10.503820 ===
TLS client: In state wait_cert_cr at ssl_handshake.erl:2136 generated CLIENT ALERT: Fatal - Handshake Failure
 - {bad_cert,hostname_check_failed}
=ERROR REPORT==== 14-Mar-2024::16:19:10.508267 ===
Failed to connect to server: Sock(TlsAlert(HandshakeFailure([84, 76, 83, 32, 99, 108, 105, 101, 110, 116, 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 119, 97, 105, 116, 95, 99, 101, 114, 116, 95, 99, 114, 32, 97, 116, 32, 115, 115, 108, 95, 104, 97, 110, 100, 115, 104, 97, 107, 101, 46, 101, 114, 108, 58, 50, 49, 51, 54, 32, 103, 101, 110, 101, 114, 97, 116, 101, 100, 32, 67, 76, 73, 69, 78, 84, 32, 65, 76, 69, 82, 84, 58, 32, 70, 97, 116, 97, 108, 32, 45, 32, 72, 97, 110, 100, 115, 104, 97, 107, 101, 32, 70, 97, 105, 108, 117, 114, 101, 10, 32, 123, 98, 97, 100, 95, 99, 101, 114, 116, 44, 104, 111, 115, 116, 110, 97, 109, 101, 95, 99, 104, 101, 99, 107, 95, 102, 97, 105, 108, 101, 100, 125])))
```

[Here](https://github.com/drew-harris/gleam-discord-bot/tree/reproduction) is a reproduction of the issue. When running properly the websocket client should recieve something like
```{"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-c-bl6z\",{\"micros\":0.0}]"]}}```
as shown in the Javascript code example

**Comment by drew-harris** [comment]
Note: the reproduction repo has stratus manually set to a clone of the project, you will need to change that to compile.

**Comment by rawhat** [comment]
Whew, holy smokes.  There were a bunch of issues at play here, but I _think_ I tackled them all.

Just pushed a new version.  I was able to connect to the Discord gateway no problem.  Hopefully that wasn't just a my computer thing 😬 

Let me know how this works for you!

**Comment by drew-harris** [comment]
Yep I was able to connect! Hopefully thats my last issue for a while. Really appreciate it

**Comment by rawhat** [comment]
I suspect you'll probably also need a public `ping` capability, so I can add that too.
