### ISSUE TITLE
connection seems to drop url parameters

### ISSUE THREAD

**Issue by bgwdotdev** [rawhat/stratus#6]
when connecting to `http://localhost:8000/ws?example=param` from what i can see and test, it appears that the connection doesn't pass the query params on-wards to the socket https://github.com/rawhat/stratus/blob/main/src/stratus.gleam#L560

Also appears like it 400 response don't actually terminate the websocket at all

Happy to have a look into it though not super familiar with the details here so any pointers would be appreciated ^^

cheers

**Comment by rawhat** [comment]
Hey thanks for the issue :)

I was dumb and was not handling query params as I should have.  The latest release has handled that.  Let me know if you run into any issues with it!

Also a good call out on handling non-success codes on the response.  That will probably be a little more work, so I will do that shortly.

**Comment by rawhat** [comment]
Okay I've added an `on_handshake_error` method to the builder.  This will get called with the `Response(BitArray)` that the server sends (if it's not a `101` status code).  The process still shuts down, which maybe I could do a little differently.  But for now, hopefully this at least gives some more actionable information.

Let me know if you run into anything!

**Comment by bgwdotdev** [comment]
brilliant, tested both params and 400 and it's all working nicely, thank very much for such a quick update, super appreciated!
