### ISSUE TITLE
Not receiving text frames from server

### ISSUE THREAD

**Issue by sneakycrow** [rawhat/stratus#7]
I'm writing a client using stratus, and running a slightly modified version of the `README.md` example. It's utilizing `gleam@0.8.0`

I can successfully connect to the remote server, receiving the expected debug logs associated with the handshake. When I send a message, I can see the debug log associated with those, but I never receive any text frames back from the server.

I checked to see if it was a server-side issue by spinning up a custom server and a different client. I validated that the server is sending the text frame, and if I use a different client I receive it.

Here's the code I'm using:
```gleam
import gleam/erlang/process
import gleam/function
import gleam/http/request
import gleam/io
import gleam/option.{None}
import gleam/otp/actor
import logging
import stratus

pub type Msg {
  Close
  Message(String)
}

pub type LogLevel {
  Debug
}

pub type Log {
  Level
}

@external(erlang, "logger", "set_primary_config")
fn set_logger_level(log: Log, level: LogLevel) -> Nil

pub fn main() {
  logging.configure()
  // NOTE:  This isn't strictly necessary at all (including the associated
  // stuff above). It's included just to show the debug logging.
  set_logger_level(Level, Debug)
  let assert Ok(req) = request.to("http://localhost:3000/ws")
  let builder =
    stratus.websocket(
      request: req,
      init: fn() { #(Nil, None) },
      loop: fn(msg, state, conn) {
        case msg {
          stratus.Text(msg) -> {
            // This never gets called
            logging.log(logging.Debug, "Received message: " <> msg)
            actor.continue(state)
          }
          stratus.User(Message(msg)) -> {
            logging.log(logging.Debug, "Sending message " <> msg)
            let assert Ok(_resp) = stratus.send_text_message(conn, msg)
            actor.continue(state)
          }
          stratus.Binary(_msg) -> {
            logging.log(logging.Debug, "Received binary message")
            actor.continue(state)
          }
          stratus.User(Close) -> {
            logging.log(logging.Debug, "Closing connection")
            let assert Ok(_) = stratus.close(conn)
            actor.Stop(process.Normal)
          }
        }
      },
    )
    |> stratus.on_close(fn(_state) { io.println("oh noooo") })

  let assert Ok(subj) = stratus.initialize(builder)

  process.sleep(3000)
  stratus.send_message(subj, Message("A message"))
  stratus.send_message(subj, Message("A second message"))

  let done =
    process.new_selector()
    |> process.selecting_process_down(
      process.monitor_process(process.subject_owner(subj)),
      function.identity,
    )
    |> process.select_forever

  io.debug(#("WebSocket process exited", done))
}
```

**Comment by rawhat** [comment]
Thanks for the issue and reproduction!  Pretty sure I know what dumb thing I did.  Working on a fix, hopefully not too involved.

**Comment by rawhat** [comment]
Okay, this was an error in a dependency I pulled some stuff out into.  It should be fixed.  I _think_ a `gleam deps update` should grab the latest version.

Do you mind trying this?  If that doesn't work, I can bump it and release a new version of this library.

**Comment by sneakycrow** [comment]
> Okay, this was an error in a dependency I pulled some stuff out into. It should be fixed. I _think_ a `gleam deps update` should grab the latest version.
> 
> Do you mind trying this? If that doesn't work, I can bump it and release a new version of this library.

Running `gleam deps update` fixed it! Thank you so much!

**Comment by rawhat** [comment]
I also released a new version anyway, with some fixes for things.  Let me know if you run into anything else!
